# Generated by Django 4.0.6 on 2022-08-06 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinomeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_api', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)])),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('image_url', models.FilePathField(blank=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='friend_relation', to='cinomeapp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.element')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.list')),
                ('visibility_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.visibilitytype')),
            ],
        ),
        migrations.CreateModel(
            name='TagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_element', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.userelement')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.listtype'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.user'),
        ),
        migrations.AddField(
            model_name='list',
            name='visibility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.visibilitytype'),
        ),
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinomeapp.elementtype'),
        ),
    ]
