# Generated by Django 4.0.6 on 2022-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinomeapp', '0002_element_elementtype_list_listtype_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='cinomeapp.user'),
        ),
        migrations.DeleteModel(
            name='UserFriends',
        ),
    ]
